name: Create GitHub Release

on:
  push: 
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write

env:
  GIT_AUTHOR_NAME: github-actions[bot]
  GIT_AUTHOR_EMAIL: noreply@mercedes-benz.com

jobs:
  create-github-release:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cycjimmy/semantic-release-action@v4
        id: release
        with:
            semantic_version: 24
            ci: true
            extra_plugins: |
              @semantic-release/commit-analyzer
              @semantic-release/release-notes-generator
              @semantic-release/github
              conventional-changelog-conventionalcommits
        env:
            GITHUB_TOKEN: ${{ github.token }}
      - name: Backmerge to develop
        shell: bash
        run: |
          git config --global user.name "${{ env.GIT_AUTHOR_NAME }}"
          git config --global user.email "${{ env.GIT_AUTHOR_EMAIL }}"
          git checkout develop
          git merge origin/main -Xours
          git push origin HEAD:develop